* Emacs Configuration 2025 - Emacs v.31.

In August 2025 I updated my Emacs binary, pulling the latest source
code from the Git repository andy building it using the standard
instructions which are included in the Readme file.

Having created the new binary, and run 'make install' you can check
the version of the running Emacs by running 'M-x version'. The output
will provide the current Emacs version (31.0.50) along with some
information about the interface support.

In most cases the Emacs initialisation files (init.el and config.org)
can be used without any modification, but it is also a good
opportunity to revisit the existing files, reconsider their structure,
and whether there are any changes or improvements that can be made.

Here we are again, putting together a configuration file for this new
iteration.

** What The Configuration File Should Do.

Because Emacs is a tool which can do so many different jobs, it is
obvious that no two users are likely to have the same use case which
they need to address in their Emacs configuration. Someone who codes
for a living will be most interested in functions which enable dealing
with any code base that they interact with, and this may include
dealing with different languages, providing linting and code checking
in those languages and compilation and debugging support. An author of
prose is more likely to look for a setup which provides a way of
bashing out their text as quickly as possible, possibly supports
grammar and spelling checking and then allows text markup to turn the
document into a suitable format for sharing with others.

While the following outlines all the functions that will need to be
enabled, there is a section that introduces the whole thing, setting
up the connection to the package management system and enabling the
all important version control using Magit.

Some tools and settings are undoubtedly of interest across different
use cases. The ability to create automatically expanding text to speed
the process of writing, version control and electric[fn:1] behaviour
is universally useful and should be enabled for all use cases. The
sort of functionality that fits in this space are things like
automatic bracket and parenthesis pairing, colouring of bracket pairs
to help track and check that brackets are balanced and line wrapping
(in almost all cases).

The next breakdown into sections is the entirely aesthetic. They don't
really change the behaviour of the text being entered, but they do
affect the appearance. This would include colour themes, font choices
and the like.

Addressing the first of the major uses for Emacs, I'll start with text
entry. These are the functions that support writing documents of
various times. Examples of these functions will include Groff/Troff
support, HTML/CSS support (using Emmet) and LaTeX using AucTeX mode,
BibTeX and related products and then potentially various forms of
Markdown (which includes Org mode used to write this configuration
file).

The second major group will be the programming support. Ideally this
would provide programming support for all the languages that I'm
interested in writing and learning. This list would include Lisp (Slime),
Clojure, Python, C/C++ and probably Rust. Relevant extra functions
will include debuggers (gdb being the obvious example), code linters
etc.

* Configuration Tree.

The following should act as a framework for adding the various
functions as outlined above.

** Package Management Configuration.

Old enough, and ugly enough, I remember when the process of adding
packages into Emacs meant finding a relevant set of instructions for
each package, usually involving unpacking the code into a folder and
then compiling it and adding the configuration to your init file. More
recently, clearly taking inspiration from the package management
paradigm used in modern Linux distributions, Emacs now has the Melpa
package storage and the packages can be installed using the
'use-package' command. To enable this approach you start by
configuring the Melpa server as a repository. This is the equivalent
of having the distribution repository configured in sources.d or
similar, depending on your distribution.

The code below defines the repository location and type (melpa and
non-gnu).

#+begin_src emacs-lisp
  ;; Configure the Melpa package repositories that will be used in
  ;; the rest of the configuration file.
  (eval-and-compile)
  (require 'package)
  (add-to-list 'package-archives
  	     '("melpa" . "https://melpa.org/packages/"))
  (add-to-list 'package-archives
  	     '("nongnu" . "https://elpa.nongnu.org/nongnu/"))
  (package-initialize)
  (package-refresh-contents)
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

** Package Installation Development Cycle.

Some notes on the development process for this configuration file.

I have previously managed to generate a configuration file which does
pretty much everything that I want it to do, but I'm keen to improve
the structure of the file, especially with a view to making it easier
to maintain and build on in the future. A part of this is the defining
of the structure for the components that the file will
include. Testing of the file as it is developed is enabled by using
the GNU Stow package. Stow is described as a link farm management
package which allows you to create and modify the links to packages or
files in order to allow rapid switching from one version to another.

I tend to use GNU Stow to manage the text based configuration files
that I use throughout my Linux setup. I have a folder:

.dotfiles2025

in my home folder. Subfolders of this folder will hold the relevant
configuration files. To help manage the setup, this second level
folder is named to help identify the software being managed. In the
case of Emacs, the obvious name would be 'emacs' but if there are
different files required then the name could include a descriptor
(dev, final etc) or the version of the program being addressed.

The subfolders under this descriptor are then the folders structure
that is created relative to the target location for the configuration
file. In Emacs the configuration file is normally located in:

~/.emacs.d/

so the full path for the stowed configuration file is:

~/.dotfiles2025/emacs/.emacs.d/(config.org and init.el)

The process of 'installing' the configuration file using GNU Stow
should be relatively straightforward. Information can be found using
'man stow', but the following shows how to change the configuration
files from one version to another.

At this point, where I am using the previous configuration file
located in:

~/.dotfiles25/emacs2024/.emacs.d/config.org

the softlink in the folder:

~/.emacs.d/

points at the files (config.org and init.el) in the above folder.

To replace the files with this local 'in development' version run:

rm -rfv ~/.emacs.d

then, from the appropriate stow folder run:

stow emacs

This will create the symlink enabling the appropriate files.

The deletion step seems to be necessary as Stow won't overwrite an
existing link as a precautionary measure.

At this point in the development, I am using the previous version of
the configuration file, but will switch into the new version for
testing purposes as the file is expanded. Then, at some point, when
most of the useful functionality is in place I will switch to this
file full time.

** Magit Version Control.

When the question is raised, why use Emacs, one of the popular answers
is the Magit package. Magit is described as a porcelain (not sure
why!), but all I know is that it is a way of doing all the Git type
actions that you might want to do within the text editor itself. The
configuration below installs the Magit package and makes the key
mapping to access the Magit functions 'C-x g'. Magit is a menu driven
system for running through the normal cycle of Git functions, such as
adding files to staging, committing updates and pushing to the
repository. It also provides the more advanced functions such as
rebasing, but these are ofter accessed using M-x and then magit-
followed by the function you require.

I have long marvelled at how seamless the Magit functionality is
within Emacs, but I hadn't realised how good this was until, at work,
I had reason to try the popular 'Visual Studio' editor from
Microsoft. This editor, like most such systems nowadays, supports the
use of version control, but it is well clunky when compared to the
mighty Magit. Like most Windows stuff, it is mouse-centric, whereas
key driven approaches are so much more graceful.

#+begin_src emacs-lisp
  ;; Enable Magit and configure the 'Git status' key mapping.
  (use-package magit
    :config (global-set-key (kbd "C-x g") 'magit-status))
#+end_src

** Helm - Command Filtering Everywhere.

Emacs got its name from the fact that it is a large number of macros
which enable you to do all sorts of clever things. The command to go
to the beginning of a line is called with C-a, but the actual macro
you are running is org-beginning-of-line (this specific macro because
this file is being written in Org Mode). The most useful commands are,
like the above, mapped to a keymapping, and there are many keymaps
employed in a single Emacs setup. But there will still be many many
commands which you don't use enough to merit assigning a keystroke
to. Fortunately Emacs provides a straightforward way to run these
macros. The key pair 'M-x' will open the transitory window at the
bottom of the Emacs window and the command can be called by typing its
name. To a certain extent, this approach does require you to remember
the command you want to use, but Helm simplifies this by providing a
filtering process. Rather than typing the full name, in the right
order, and with the appropriate hyphens, type the words that you
expect to be in the macros command name and the displayed list of
macros will filter down until you are left with a handful of possible
candidates, or in many cases, just the command that you want.

When the filtering has reduced the number of options to a suitably
small number then the required macros can be selected, moving the
selection bar up or down using C-n (next) or C-p (previous) as
appropriate.

The Helm configuration below activates the Helm function and
configures a few popular Helm specific activities:

- Helm 'Find Files': M-<F5>
- Helm 'Buffers List': <F10>
- Helm 'Recent Files': S-<F10>

It is worth considering highlighting these keys in a Conky template at
some point, otherwise I will never use them! Checking just now, they
do all work as expected!

#+begin_src emacs-lisp
  ;; Activate helm, the filtering function.
  (use-package helm
    :bind (("M-x" . helm-M-x)
  	 ("M-<f5>" . helm-find-files)
  	 ([f10] . helm-buffers-list)
  	 ([S-f10] . helm-recentf))
    :config
    (helm-mode 1)
    (helm-autoresize-mode))
#+end_src

Practice makes perfect when it comes to using Helm. Use it and gain familiarity!

** Aesthetics Settings.

The next bunch of settings are not really necessary, but they do make
Emacs look prettier and easier on the eye.

*** Minimise the Screen Furniture in the Emacs Window.

Out of the box, Emacs has a menu bar, toolbar (complete with icons)
and the like. These are unnecessary because we'll be driving all the
usage through the keyboard.

#+begin_src emacs-lisp
  ;; Minimise the screen furniture.
  (menu-bar-mode 0)			; no menu bar
  (tool-bar-mode 0)			; no tool bar
  (blink-cursor-mode 0)			; steady cursor rather than blinking
  (scroll-bar-mode 0)			; no scroll bar... save the real estate
  (display-battery-mode 1)			; battery info in the mode line.
#+end_src

The line about displaying the time in the modeline has been removed
because I'll be using the Doom modeline which doesn't seem to support
time usage.

*** Don't Show the Splash Screen.

I usually start Emacs in the client mode so that it connects to a
daemon module (which is launched automatically if it isn't already
running). Because of this, I don't normally have a problem with the
splash screen being displayed. However, I don't want it displayed,
even if I run Emacs as a standalone instantiation. The following
switches off the splash screen.

#+begin_src emacs-lisp
  ;; Splash screen be gone!
  (setq inhibit-startup-message t)
#+end_src

*** Do Show a Pithy Quote Instead.

As the splash screen has been deactivated, the scratch buffer is
displayed by default. On its own it will contain some pretty dull text
about using the buffer. But who wants to settle for that.

The setting below is derived from a version I came up with when
working at the University. At that stage I had the same configuration
file in use at home and at work, so liked the idea of a different text
phrase being displayed in the different locations. This was achieved
by filtering on the system name and using this to select the
text. I'll leave it in place in case I start using the configuration
in multiple locations.

#+begin_src emacs-lisp
        ;; Display pithy text on the basis of system name
        (if (string=(system-name) "ziggyi5")
            (setq initial-scratch-message
    		"\n\n\n\n\t\t\tOnce upon a midnight dreary, while I pondered, weak and weary,
  \t\t\tOver many a quaint and curious volume of forgotten lore,
  \t\t\tWhile I nodded, nearly napping, suddenly there came a tapping,
  \t\t\tAs of some one gently rapping, rapping at my chamber door. “
  \t\t\t“'Tis some visitor,” I muttered, “tapping at my chamber door—
  \t\t\tOnly this, and nothing more.”"))
  (if (string=(system-name) "uk-rfieldse-l")
      (setq initial-scratch-message
  	    "Everything's science-fiction until someone makes it science fact.\n\nMarie Lu"))
#+end_src

*** Select A Dark Colour Theme.

I like to use a dark theme in Emacs (as I do in most of the programs
that I use), and there are a huge number available in Emacs. My
preference is for one with a relatively dark background, but with
fairly colourful font colourisation for the text as this helps in
reading the structure of things like code and markup.

There is a useful gallery website which shows examples of the various
themes available. This can be found here:

https://emacsthemes.com/

I'm going to go with 'Catppuccin' for the time being. There is a
development repository for the theme here:

https://github.com/catppuccin/emacs

But it is also in the Melpa repositories, so can be installed using
the same use-package commands.

#+begin_src emacs-lisp
        ;; Catppuccin Machiato theme
        (use-package catppuccin-theme
          :ensure t
          :config (setq catppuccin-flavor 'macchiato)
  	(catppuccin-reload))
#+end_src

I do like the new theme, especially the colours of the markup language entries.

*** Set A Nice Font.

A popular subject on the Emacs Porn sub-reddit is the font that people
like to use with Emacs. I've regularly settled on some version of
Hack, so I'm going to stick with that.

#+begin_src emacs-lisp
  ;; Set the font to Hack, and experiment a little with the size.
  (add-to-list 'default-frame-alist '(font . "Hack-11"))
  (set-face-attribute 'default nil
  		    :family "Hack")
#+end_src

Setting the font to size 7 might be a step too far, but I'll use it
for a little while, see how I get on.

*** Modify Frame Title to Useful Text.

The standard text in the frame heading has the form:

filename - GNU Emacs at ziggyi5

While this does give you the bare information, it could be more
useful.

#+begin_src emacs-lisp
  ;; Modify frame title from:
  ;; filename - GNU Emacs at system name
  ;; to
  ;; Emacs - Buffer: > File
  (setq frame-title-format '("Emacs - Buffer: %b > File: %f"))
#+end_src

This approach displays the buffer name and the file (including path)
in the frame title bar.

*** Highlighting the Current Line.

Sometimes it can be difficult to locate the line that you are working
on. This setting switches on highlighting for the line that the cursor
is currently on, to make it easier to find where you are.

This is one of the first settings that feels like it could be added
either as a purelf aesthetic entry or as a 'behaviour that is useful
in all modes'. Currently I'm going to treat it as an aesthetic
setting, but it could live in the alternate location just as readily.

#+begin_src emacs-lisp
  ;; Turn on highlighiing of the current line.
  (global-hl-line-mode 1)
#+end_src

*** Replace Standard Modeline with Doom Emacs Version.

The Modeline is the information line just above the bottom of the
active Emacs window. The standard version is fine, informative, but
the Doom Emacs version uses the Nerd Font to highlight the file type.

#+begin_src emacs-lisp
  ;; Activate the Doom Mode Line.
  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1))
#+end_src

If the icon on the Doom Modeline shows a Unicode character then the
required font isn't installed. Google for instructions on installing
the Doom Modeline fonts for instructions.

*** Emacs Window Transparency Settings.

Transparency in Emacs relies on a functioning Compositor. The i3wm
doesn't use the same compositor as Gnome or KDE, so it needs to be
installed and configured separately. Once it is running it can be
configured to different levels of transparency.

#+begin_src emacs-lisp
  ;; Transparency - super groovy!
  (set-frame-parameter (selected-frame) 'alpha '(80 50))
  (add-to-list 'default-frame-alist '(alpha 80 50))
#+end_src

The 80/50 configure the transparency for the active and inactive modes.

** Behaviours That Are Useful In All The Modes.
*** Parenthesis Pairing - add the closing bracket automatically.

Parenthesis pairing is provided by the use of 'electric
behaviour'. Once this is set up then adding the opening bracket will
trigger adding the closing bracket and will place the cursor between
the two brackets.

The brackets in this case includes:

parenthesis - ()
square brackets - []
curly brackets - {}
speech marks - ""
single quotes - ''

When writing Lisp the pairing of single quotes can be a pain, but I
don't do enough Lisp to make me want to fix this. This may change in
the future.

#+begin_src emacs-lisp
  ;; Electric Brackets
  (use-package electric
    :ensure t
    :init
    :config (add-hook 'prog-mode-hook 'electric-pair-mode)
    :config (add-hook 'LaTeX-mode-hook 'electric-pair-mode)
    :config (add-hook 'latex-mode-hook 'electric-pair-mode)
    :config (add-hook 'text-mode-hook 'electric-pair-mode)
    :config (add-hook 'org-mode-hook 'electric-pair-mode)
    :config (add-hook 'pov-mode-hook 'electric-pair-mode))
#+end_src

*** Rainbow Colouring Of Brackets - Useful to check bracket pairing

Emacs provides an excellent method of managing brackets by using
electric brackets (see 'Parenthesis Pairing'), but this function also
helps you track the brackets by colouring the opening and closing
brackets the same colour.

#+begin_src emacs-lisp
  ;; Rainbow Delimiters (this needs setting for relevant modes).
  (use-package rainbow-delimiters
    :ensure t
    :init
    :config (add-hook 'prog-mode-hook 'rainbow-delimiters-mode)
    :config (add-hook 'LaTeX-mode-hook 'rainbow-delimiters-mode)
    :config (add-hook 'latex-mode-hook 'rainbow-delimiters-mode)
    :config (add-hook 'text-mode-hook 'rainbow-delimiters-mode)
    :config (add-hook 'org-mode-hook 'rainbow-delimiters-mode)
    :config (add-hook 'pov-mode-hook 'rainbow-delimiters-mode))
#+end_src

*** Bracket/Parenthesis Pair Highlighting Function.

The rainbow colouring of brackets and adding brackets as pairs both
provide excellent, reliable methods to ensure brackets are
balanced. The following setting provides another method, highlighting
the other half of each pair when the cursor is in place.

#+begin_src emacs-lisp
  ;; Highlight the other half of a matching pair when the cursor is
  ;; on a bracket or similar.
  (show-paren-mode 1)
#+end_src

*** Spell Checking - Check Spelling Against UK British Dictionary.

#+begin_src emacs-lisp
    ;; spellchecking
    (setq ispell-program-name "/usr/bin/aspell")
    (setq ispell-dictionary "british"
          ispell-extra-args '() ;; TeX mode "-t"
    	ispell-silently-savep t)

    ;; Configure a personal dictionary
    (setq ispell-personal-dictionary "~/.backups/ispell-personal-dictionary")
    ;; flyspell
    (use-package flyspell
      :ensure t
      :init
      :config (add-hook 'text-mode-hook 'flyspell-mode)
      :config (add-hook 'prog-mode-hook 'flyspell-mode)
      :config (add-hook 'LaTeX-mode-hook 'flyspell-mode)
      :config (add-hook 'latex-mode-hook 'flyspell-mode)
      :config (add-hook 'org-mode-hook 'flyspell-mode)
      :config (define-key flyspell-mode-map (kbd "C-,") 'helm-flyspell-correct))
#+end_src

*** Grammar Checking - Flycheck For Other Types of Language Checking.

#+begin_src emacs-lisp
  ;; install and configure flycheck
  (use-package flycheck
    :ensure t
    :init (global-flycheck-mode))
#+end_src

*** Global Line Numbering.

Back when I first started playing around with computers, back when ZX
Spectrums were cutting edge and BASIC was the programming language of
choice, writing programs involved putting a number at the beginning of
every line, usually incremented in 10s in order to leave space for
extra lines if required.

Most other languages don't require the numbering of lines, but it can
still be useful to get an idea of how many lines your file has, and it
can ever provide a way of navigating the file quickly. To support
this, I'm now going to switch on the displaying of the line number at
the left hand edge of the Emacs frame.

#+begin_src emacs-lisp
  ;; Activate line numbering
  (global-display-line-numbers-mode t)
#+end_src

The number can be used to navigate around using:

M-g g or M-g M-g and then type the line number to move to.

Of course, moving to the beginning or end of the file you can use M-<
and M->. Otherwise search for text as a quick way of getting around.

One point of note is the line numbering when using folding. Folding is
a great way of being able to focus on a specific part of the text. If
working appropriately, using Tab can cycle the visibility of a section
of the file by folding (hiding) the section of text. The global
numbering counts these lines even though they aren't visible. This
means that this file leaps from 73-107, from 107-178 etc. Entering a
line number which is hidden will cause the section to be opened.

*** Line Wrapping Everywhere and Every Mode.

By default, Emacs doesn't have line-wrapping switched on by
default. The following is the configuration to activate the line wrap.

#+begin_src emacs-lisp
  ;; Activate auto-fill mode as a minor mode for all the popular modes
  (add-hook 'text-mode-hook 'turn-on-auto-fill)
  (add-hook 'LaTeX-mode-hook 'turn-on-auto-fill)
  (add-hook 'latex-mode-hook 'turn-on-auto-fill)
  (add-hook 'org-mode-hook 'turn-on-auto-fill)
  (add-hook 'emacs-lisp-mode-hook 'turn-on-auto-fill)
  (add-hook 'fundamental-mode-hook 'turn-on-auto-fill)
  (add-hook 'prog-mode-hook 'turn-on-auto-fill)
#+end_src

Using 'prog-mode-hook' activates the wrapping for all manner of
programming modes.

*** Backup File Management.

The default backup behaviour for Emacs is to create a copy of the file
that is being backed up but with attached number tags ~<no.>~ stored
in the same directory as the original. This can lead to a number of
random files filling these folders up.

The reconfigured version saves these backups into a shared folder, in
my case ~/.backups/

#+begin_src emacs-lisp
  ;; set backup target directory and behaviour
  (setq backup-directory-alist
        '(("." . "~/.backups/")))
  (setq backup-by-copying t
        delete-old-versions t
        kept-new-versions 2
        kept-old-versions 2
        version-control t)
#+end_src

*** Return To The Previous Location In The File.

When working on a project, it is likely you'll need to keep on
returning to a small subset of files and, in many cases to the same
locations. The following configures this and saves the information
into a file in the backup folder.

#+begin_src emacs-lisp
  ;; SavePlace behaviour - back to your last location
  (save-place-mode 1)
  (setq save-place-file "~/.backups/.places")
#+end_src

*** Emacs Command History Persistence Using savehist.

When working on the command line, one of the really useful functions
is to be able to recall previous commands that have been entered in
Bash. This can be done using either the command 'history' or using C-r
to search backwards through the command list.

A similar function for Emacs is provided by using a history file,
configured below.

#+begin_src emacs-lisp
  ;; Persistent command history between Emacs sessions.
  (setq savehist-file "~/.backups/emacs-history"
        history-length t
        history-delete-duplicates t
        savehist-save-minibuffers-history 1
        savehist-additional-variables
        '(kill-ring
  	search-ring
  	regexp-search-ring))
  (savehist-mode 1)
#+end_src

*** White Space Trimming.

It is often the case that, when working repeatedly on a single file
then that file can end up having extra white space added or left over
at the end of the file. This can happen because of text deleted
during the editing phase, or just from random extra lines being added
when the text is being written. The following function removes
excessive text from the end of a document. It is also useful when the
files are under version control because extra lines at the end of a
document may trigger the document being considered a new version.

This approach also removes extra characters at the end of the lines in
the document. There is discussion on providing this functionality in
the Emacs Wiki page on white space removal.

#+begin_src emacs-lisp
  ;; Remove blank lines from the end of the file.
  (add-hook 'before-save-hook 'delete-trailing-whitespace)
#+end_src

The function is one of the first in the file to be added to the list
of functions activated when a particular event is taking place. In
this case the 'delete-trailing-whitespace function is executed when
the file is saved.

A useful note for functions of this type is how you can find
information on what they do. M-x describe function and then enter the
function name, and you'll see a guide on what the function actually
does, along with any modifications available in the command.

*** Simplified Response for Yes/No Questions.

The default behaviour for Emacs when requiring yes/no answers is for
the answer to be the full word in each case. The following function
simplifies this to y/n.

#+begin_src emacs-lisp
  ;; Use y/n rather than yes/no
  (fset 'yes-or-no-p 'y-or-n-p)
#+end_src
** Writing Prose And Documents.

*** Groff/Troff Editing

*** HTML/CSS Editing Using Emmet

*** LaTeX Using AucTeX/BibTeX/RefTeX.

*** Manage the Bibliographic Databases Using eBib.

*** Markdown and Org Mode Document Preparation.

** Programming Modes and Support.

*** Makefile.

*** Lisp/Clojure.

*** Python.

*** C/C++.

*** Rust.

*** Debugging.

* Footnotes

[fn:1] In Emacs, the term 'electric' behaviour refers to extra
behaviour triggered when various keys are pressed. The term is most
often used to describe the enter or return key moving the cursor to
the next line (the usual behaviour) and also carry out the action that
adding the tab key would provide. In writing code the electric
behaviour will indent the next line, especially useful when writing an
indent sensitive language such as Python.
